<?php $items = $block->getCategoryFaqItems(); ?>
<?php if ($items->getSize()) : ?>
    <div class="etatvasoft-faq-block">
        <?php
        if ($this->getData("categoryfaqlabel")) {
            ?>
            <div class="content-heading">
                <h1 class="title"><?php /* @escapeNotVerified */ echo __($this->getData("categoryfaqlabel")) ?></h1>
            </div>
            <?php
        }
        ?>
        <?php
        $count = 1;
        foreach ($items as $item) : ?>
            <?php if($item->getis_active()==1 && strpos($item->getcategoryfaq_categories_ids(),$block->getCurrentCategory()) > -1 ) :?>
            <div class="accordion">
                <div class="block">
                    <p class="question">
                        <strong>
                            <span><?php echo $count; ?>. <?php echo $item->getcategoryfaq_question() ?></span>
                        </strong>
                    </p>
                    <div class="answer content">
                        <?php echo $item->getcategoryfaq_answer() ?>
                    </div>
                </div>
            </div>
        <?php endif?>
        <?php
        $count++;
        endforeach; ?>
    </div>
    <script>
        require(['jquery'],function(jQuery){
            jQuery(document).ready(function () {
                jQuery(".accordion .question").click(function () {
                    jQuery(this).closest(".accordion").siblings().find('.open').removeClass('open');
                    jQuery(this).closest(".accordion").siblings().find(".answer").stop(true, true).slideUp();
                    jQuery(this).toggleClass('open').closest(".accordion").find(".answer").stop(true, true).slideToggle();
                });
            });
        });
    </script>
<?php endif; ?>
